### ISSUE TITLE
Any possibility of a port/patch to make this compatible with the GT:CEU port of Nomifactory?

### ISSUE THREAD

**Issue by rabbitchemicals** [MDMeaux/GregMeth#1]
Out of the box this just crashes the game (ID conflicting with draconium or something) and trying to reassign material IDs myself results in other things (probably definitely necessary for a meth-free run) just straight up disappearing, taken by the gripping plague of the meth business, lost within the initialization slums of ghost materials and incomprehensible numbers, lost without any phone to call Saul, Broken and Bad. Material ID numbering is absolutely incomprehensible to me cause all my foolish calculations to figure out which values should logically be free prove to be fruitless (but at least there's meth)

uhh tl;dr material IDs are stupid?

**Comment by rabbitchemicals** [comment]
figured it out

**Comment by dckrell** [comment]
how did you get it to work tho

**Comment by dckrell** [comment]
nvm just had to change the id of the liquid into something else thats higher

**Comment by dckrell** [comment]
figured it out, just change the ids by 100 (go to the gregmeth_materials then find all the "MaterialBuilders" and change the 320xx into a 321xx) and that it

**Comment by dckrell** [comment]
figured it out :trollface: (go to the gregmeth_materials.zs change the funny 320xx numbers into 327xx aka changing the 0 in the middle to a 7...)
